---
# supported frameworks: mocha|jest|jasmine
framework: mocha


preRun:

  command:
    - npm install
    

postMerge:

  pattern:
     - "test/testScripts/**/*.js"
  

preMerge:
  pattern:
  - "test/testScripts/**/*.js"



postRun:

  command:
    - node --version


configFile: mocharc.yml

# provide the semantic version of nodejs required for your project
nodeVersion: 17.6.0

# configure whether to smartSelect test-cases. Default true
smartRun: false

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
#version: 1.0